function sw = surfel_weights()
% returns a cell array, where each elements corresponds to a surfel, and in
%   every cell there are 3 more cells, corresponding to the pgrams
%   generated by the applicable lattice velocities. Each of these cells
%   contains a variable number of weights, correponding to the lattice 
%   cell touched by the cell's pgram. 

