function sw = surfel_weights(p0,v1,v2,dh)
% Catered to lid driven cavity case.
% returns a 2d cell array, where each row corresponds to a surfel, and 
%   each column corresponds to the pgrams
%   generated by the applicable lattice velocities. Each of these cells
%   contains a variable number of weights, correponding to the lattice 
%   cell touched by the cell's pgram.
% each row entry inside cells are: [i,j, weight, overlap_area]
% As can be inferred, the number of lattice vectors are the same for all
%   segments.

% p0: starting points for every surfel.
% v1: one defining edge of the pgram, common among all pgrams in this case.
% v2: other defining edges of the pgrams corresponding to lattice vectors.

nsurfels = size(p0,1);
nvectors = size(v2,1);

sw = cell(nsurfels,nvectors);
for r = 1:nsurfels
    for c = 1:nvectors
        pgram_area = norm(cross([v1,0],[v2(c,:),0]),2);
        pw = pgram_weights(p0(r,:),v1,v2(c,:),dh);
        pw(1,4) = 0;
        sw{r,c} = pw;
        sw{r,c}(:,4) = sw{r,c}(:,3);
        sw{r,c}(:,3) = sw{r,c}(:,3) / pgram_area;
    end
end
    
    
    
    